babel だと 型定義をチェックしないので問題なかったが next-jest だとチェックしてくれるので render の型定義が2パターンありどちらに override するべきか判断つかないので customRender をそのまま export する形にした
TypeError: Cannot set property render of [object Object] which has only a getter